server:
    port: 8082

spring:
    application:
        name: media-service
    config:
        import: "optional:configserver:http://localhost:8888"

gcp:
    project-id: project-fb6d543f-c464-45a3-8d9
    credentials:
        location: /project-fb6d543f-c464-45a3-8d9-a94b947a4042.json